name: test CICD

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs: 
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code 
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}  

            - name: Verify Docker login
              run: |
                docker info
                docker images

            - name: Building the Docker Image
              run: docker build -t <dockerhub_username>/<image_name>:latest .
            
            - name: Pushing Image to Docker Hub
              run: docker push <dockerhub_username>/<image_name>:latest

    

            ## Running on AWS
            - name: Deployment to AWS
              uses: appleboy/ssh-action@master
              with: 
                host: ${{secrets.AWS_IP_ADDRESS}}
                username: ${{secrets.AWS_USER_NAME}}
                key: ${{secrets.AWS_SSH_KEY}}
                script: |
                    docker pull <dockerhub_username>/<image_name>:latest
                    docker stop <container_name> || true
                    docker rm <container_name> || true
                    docker run -d -p 8000:8000 --name <container_name> <dockerhub_username>/<image_name>:latest